# Generated by Django 6.0.1 on 2026-01-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QBOAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QBO company/realm ID', max_length=50, unique=True)),
                ('company_name', models.CharField(blank=True, help_text='Company name from QBO', max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, help_text='Current access token', null=True)),
                ('refresh_token', models.TextField(help_text='OAuth refresh token (rotates on refresh!)')),
                ('access_token_expires_at', models.DateTimeField(blank=True, help_text='When access token expires', null=True)),
                ('is_token_expired', models.BooleanField(default=False, help_text='True if re-authorization is required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QBO Account',
                'verbose_name_plural': 'QBO Accounts',
                'db_table': 'qbo_accounts',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qbo_id', models.CharField(help_text='The QBO Invoice.Id', max_length=50)),
                ('customer_ref', models.CharField(blank=True, db_index=True, help_text='CustomerRef.value from QBO', max_length=50, null=True)),
                ('raw_data', models.JSONField(help_text='Full JSON payload from QBO')),
                ('sync_token', models.CharField(blank=True, help_text='QBO sync token', max_length=50, null=True)),
                ('last_updated_time', models.DateTimeField(blank=True, help_text='Metadata.LastUpdatedTime from QBO', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='QBO account this invoice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='qbo_ingestion.qboaccount')),
            ],
            options={
                'db_table': 'invoices',
                'indexes': [models.Index(fields=['account', 'qbo_id'], name='invoices_account_c5654a_idx'), models.Index(fields=['account', 'customer_ref'], name='invoices_account_e4e104_idx')],
                'unique_together': {('account', 'qbo_id')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qbo_id', models.CharField(help_text='The QBO Customer.Id', max_length=50)),
                ('raw_data', models.JSONField(help_text='Full JSON payload from QBO')),
                ('sync_token', models.CharField(blank=True, help_text='QBO sync token for optimistic locking', max_length=50, null=True)),
                ('last_updated_time', models.DateTimeField(blank=True, help_text='Metadata.LastUpdatedTime from QBO', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='QBO account this customer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='qbo_ingestion.qboaccount')),
            ],
            options={
                'db_table': 'customers',
                'indexes': [models.Index(fields=['account', 'qbo_id'], name='customers_account_0f9856_idx')],
                'unique_together': {('account', 'qbo_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('Customer', 'Customer'), ('Invoice', 'Invoice')], help_text='Type of object being synced', max_length=20)),
                ('last_attempt_time', models.DateTimeField(blank=True, help_text='When sync was last attempted', null=True)),
                ('last_successful_sync_time', models.DateTimeField(blank=True, help_text='When sync last succeeded', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Current sync status', max_length=20)),
                ('checkpoint', models.CharField(blank=True, help_text='LastUpdatedTime checkpoint for incremental sync', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Last error message', null=True)),
                ('consecutive_failures', models.IntegerField(default=0, help_text='Number of consecutive failures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='QBO account', on_delete=django.db.models.deletion.CASCADE, related_name='sync_states', to='qbo_ingestion.qboaccount')),
            ],
            options={
                'db_table': 'sync_states',
                'indexes': [models.Index(fields=['account', 'object_type'], name='sync_states_account_2060b2_idx')],
                'unique_together': {('account', 'object_type')},
            },
        ),
    ]
